### ISSUE TITLE
Add link to your IRIS-HEP Fellowship final presentation to README

### ISSUE THREAD

**Issue by msneubauer** [Neubauer-Group/UFOManager#19]
Add link to your IRIS-HEP Fellowship final presentation to the README file

[](https://indico.cern.ch/event/1195270/contributions/5043771/attachments/2508513/4311003/Zijun_Wang_IRIS-HEP_Presentation.pdf)

Maybe you could add a "References" section at the end? Also will be useful for link to paper to be posted

@yorkiva @ThanosWang

**Comment by yorkiva** [comment]
The links to the presentation and paper are added in the README reference
